import type { Metadata } from "next";
import LocalFont from "next/font/local";

import "tailwindcss/tailwind.css";

const pretendard = LocalFont({
  src: "../public/fonts/PretendardVariable.woff2",
});

const modernDOS = LocalFont({
  src: "../public/fonts/modernDOS.woff2",
  variable: "--font-modern-dos",
});

export const metadata: Metadata = {
  title: "bashruv's lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} ${modernDOS.variable} text-white`}
      >
        {children}
      </body>
    </html>
  );
}
